In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('gurgaon_properties.csv')

In [4]:
df.shape

(3961, 20)

In [5]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
3947,3 BHK Flat in Sector 92 Gurgaon,flat,sare crescent parc,0.82,5384.0,1523.0,Built Up area: 1523 (141.49 sq.m.),3,3,3+,not available,"Sector 92, Sector 92 Gurgaon, Gurgaon, Haryana",12.0,West,undefined,NaN,3bhk multistorey apartment for resale in sare ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area4 out of 5', 'Amenities3 out of 5'..."
476,9 Bedroom House for sale in C Block Sushant Lo...,house,independent,14.00,39886.0,3510.0,Plot area 390(326.09 sq.m.),9,9,3+,servant room,"C Block Sushant Lok Phase 1, Gurgaon, Haryana",4.0,North,5 to 10 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Corner building,north facing,good location,",NaN,['Water Storage'],"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1637,3 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,1.98,9036.0,2191.0,Super Built up area 2191(203.55 sq.m.),3,3,3+,study room,"1203, Sector 37D Gurgaon, Gurgaon, Haryana",12.0,North-East,0 to 1 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",Its ultra luxury apartment and society,"['1 Stove', '6 AC', '1 Chimney', '1 Modular Ki...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
2082,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.58,13739.0,1150.0,Carpet area: 1150 (106.84 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",3.0,South,Within 6 months,"['Sector 55-56 Metro station', 'Bestech Centra...",It is a 2.5 bhk unit with a lockable space in ...,"['1 Fan', '1 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Park', 'Visitor Parking']",NaN
843,8 Bedroom House for sale in DLF Phase 3,house,independent,11.00,28898.0,3806.0,Plot area 3806.45(353.63 sq.m.)Built Up area: ...,8,11,3+,"pooja room,study room,servant room,others","Dlf -3, DLF Phase 3, Gurgaon, Haryana",3.0,East,10+ Year Old,NaN,Independent house available for sale.,"['8 Wardrobe', '12 Fan', '1 Exhaust Fan', '8 G...","['Private Garden / Terrace', 'Swimming Pool', ...","['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [6]:
df.duplicated().sum()

0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [8]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [9]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,1.60,7302.0,2191.0,Super Built up area 2191(203.55 sq.m.)Built Up...,4,3,3+,others,"A701, Sector 37D Gurgaon, Gurgaon, Haryana",7.0,North,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",This is a super luxury property which is situa...,"['1 Wardrobe', '5 Fan', '1 Exhaust Fan', '21 L...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1,4 BHK Flat in Sector 1A IMT Manesar,flat,dlf express greens,1.60,6808.0,2350.0,Carpet area: 2350 (218.32 sq.m.),4,6,3+,"study room,pooja room,servant room","Sector 1A IMT Manesar, Gurgaon, Haryana",4.0,North-East,1 to 5 Year Old,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",East facing and cornet flat plus also park fac...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction3.5 out ..."
2,3 BHK Flat in Sector 82 Gurgaon,flat,mapsko royale ville,1.12,8000.0,1400.0,Super Built up area 1790(166.3 sq.m.)Built Up ...,3,4,2,"pooja room,servant room","000, Sector 82 Gurgaon, Gurgaon, Haryana",6.0,North-West,1 to 5 Year Old,"['Sapphire 83 Mall', 'Golf Course Ext Rd', ""St...",Mapsko royale ville is one of gurgaon's most s...,"['4 Fan', '1 Exhaust Fan', '7 Light', '1 Modul...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction3 out ..."
3,3 BHK Flat in Sector 90 Gurgaon,flat,dlf regal gardens,1.25,7339.0,1703.0,Super Built up area 1703(158.21 sq.m.),3,3,3,servant room,"123, Sector 90 Gurgaon, Gurgaon, Haryana",28.0,North,5 to 10 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",This 3 bhk apartment is available for sale in ...,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction4.5 out ..."
4,3 BHK Flat in Sector 92 Gurgaon,flat,sare green parc,0.85,6741.0,1261.0,Built Up area: 1261 (117.15 sq.m.),3,2,2,not available,"Sector 92, Sector 92 Gurgaon, Gurgaon, Haryana",14.0,NaN,undefined,"['Huda city centre metro station', 'Iffco chow...",Multistorey apartment is available for sale. I...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."

## Initial sector feature extraction method

In [10]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [11]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,Sector 37D,1.60,7302.0,2191.0,Super Built up area 2191(203.55 sq.m.)Built Up...,4,3,3+,others,"A701, Sector 37D Gurgaon, Gurgaon, Haryana",7.0,North,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",This is a super luxury property which is situa...,"['1 Wardrobe', '5 Fan', '1 Exhaust Fan', '21 L...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1,4 BHK Flat in Sector 1A IMT Manesar,flat,dlf express greens,Sector 1A IMT Manesar,1.60,6808.0,2350.0,Carpet area: 2350 (218.32 sq.m.),4,6,3+,"study room,pooja room,servant room","Sector 1A IMT Manesar, Gurgaon, Haryana",4.0,North-East,1 to 5 Year Old,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",East facing and cornet flat plus also park fac...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction3.5 out ..."
2,3 BHK Flat in Sector 82 Gurgaon,flat,mapsko royale ville,Sector 82,1.12,8000.0,1400.0,Super Built up area 1790(166.3 sq.m.)Built Up ...,3,4,2,"pooja room,servant room","000, Sector 82 Gurgaon, Gurgaon, Haryana",6.0,North-West,1 to 5 Year Old,"['Sapphire 83 Mall', 'Golf Course Ext Rd', ""St...",Mapsko royale ville is one of gurgaon's most s...,"['4 Fan', '1 Exhaust Fan', '7 Light', '1 Modul...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction3 out ..."
3,3 BHK Flat in Sector 90 Gurgaon,flat,dlf regal gardens,Sector 90,1.25,7339.0,1703.0,Super Built up area 1703(158.21 sq.m.),3,3,3,servant room,"123, Sector 90 Gurgaon, Gurgaon, Haryana",28.0,North,5 to 10 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",This 3 bhk apartment is available for sale in ...,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction4.5 out ..."
4,3 BHK Flat in Sector 92 Gurgaon,flat,sare green parc,Sector 92,0.85,6741.0,1261.0,Built Up area: 1261 (117.15 sq.m.),3,2,2,not available,"Sector 92, Sector 92 Gurgaon, Gurgaon, Haryana",14.0,NaN,undefined,"['Huda city centre metro station', 'Iffco chow...",Multistorey apartment is available for sale. I...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."

In [12]:
df['sector'] = df['sector'].str.lower()

In [13]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,sector 37d,1.60,7302.0,2191.0,Super Built up area 2191(203.55 sq.m.)Built Up...,4,3,3+,others,"A701, Sector 37D Gurgaon, Gurgaon, Haryana",7.0,North,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",This is a super luxury property which is situa...,"['1 Wardrobe', '5 Fan', '1 Exhaust Fan', '21 L...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1,4 BHK Flat in Sector 1A IMT Manesar,flat,dlf express greens,sector 1a imt manesar,1.60,6808.0,2350.0,Carpet area: 2350 (218.32 sq.m.),4,6,3+,"study room,pooja room,servant room","Sector 1A IMT Manesar, Gurgaon, Haryana",4.0,North-East,1 to 5 Year Old,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",East facing and cornet flat plus also park fac...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction3.5 out ..."
2,3 BHK Flat in Sector 82 Gurgaon,flat,mapsko royale ville,sector 82,1.12,8000.0,1400.0,Super Built up area 1790(166.3 sq.m.)Built Up ...,3,4,2,"pooja room,servant room","000, Sector 82 Gurgaon, Gurgaon, Haryana",6.0,North-West,1 to 5 Year Old,"['Sapphire 83 Mall', 'Golf Course Ext Rd', ""St...",Mapsko royale ville is one of gurgaon's most s...,"['4 Fan', '1 Exhaust Fan', '7 Light', '1 Modul...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction3 out ..."
3,3 BHK Flat in Sector 90 Gurgaon,flat,dlf regal gardens,sector 90,1.25,7339.0,1703.0,Super Built up area 1703(158.21 sq.m.),3,3,3,servant room,"123, Sector 90 Gurgaon, Gurgaon, Haryana",28.0,North,5 to 10 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",This 3 bhk apartment is available for sale in ...,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction4.5 out ..."
4,3 BHK Flat in Sector 92 Gurgaon,flat,sare green parc,sector 92,0.85,6741.0,1261.0,Built Up area: 1261 (117.15 sq.m.),3,2,2,not available,"Sector 92, Sector 92 Gurgaon, Gurgaon, Haryana",14.0,NaN,undefined,"['Huda city centre metro station', 'Iffco chow...",Multistorey apartment is available for sale. I...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."

In [14]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 65                                                     90
sector 90                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 48                                                     56
sector 89                                                     56
sector 70a                                                    54
sector 70                                                     53
nirvana country                                               53
sector 37c                                                    53
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 2                                                   43
sector 113                                                    43
dlf phase 1                                                   43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 71                                                     27
laxman vihar                                                  27
sector 54                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 88a                                                    23
sector 33                                                     23
sector 67a                                                    22
sector 111                                                    22
dlf phase 3                                                   22
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 63a                                                    18
sector 74                                                     18
sector 91                                                     17
sector 62                                                     17
sector 110                                                    16
sushant lok phase 3                                           16
sector 99                                                     16
sector 14                                                     15
sector 60                                                     15
sector 63                                                     15
gwal pahari                                                   14
dlf phase 5                                                   14
sector 76                                                     14
sector 53                                                     14
rajendra park                                                 14
sector 52                                                     14
sector 1 imt manesar                                          14
sector 3                                                      14
laxman vihar phase 2                                          13
sector 46                                                     13
sector 36a                                                    13
sector 50                                                     12
sector 31                                                     12
sector 38                                                     12
uppals southend                                               12
sector 39                                                     12
sohna road                                                    12
sector 93                                                     12
sector 9a                                                     11
sector 47                                                     11
ashok vihar phase 3 extension                                 11
sector 7                                                      10
sector 1a imt manesar                                         10
ashok vihar phase 2                                            9
sector 4                                                       9
sector 95a                                                     9
south city 1                                                   9
sector 55                                                      9
sector 59                                                      8
malibu town                                                    8
palam vihar extension                                          8
dwarka expressway                                              8
sector 40                                                      8
sector 10a                                                     8
sector 57                                                      8
sector 89 a                                                    8
c block sushant lok phase 1                                    8
mehrauli  road                                                 8
sector 43                                                      8
mianwali colony                                                7
sector 58                                                      7
sector 36 sohna                                                7
sector 26                                                      7
surat nagar 1                                                  7
new colony                                                     7
sector 11                                                      7
sector 51                                                      7
jacobpura                                                      6
jyoti park                                                     6
sector 5                                                       6
sector 1                                                       6
ashok vihar                                                    6
rajiv nagar                                                    6
chakkarpur                                                     5
arjun nagar                                                    5
sector 105                                                     5
sector 23a                                                     5
sector 80                                                      5
sector 2                                                       5
ansal plaza                                                    5
saraswati vihar                                                5
new palam vihar                                                5
dayanand colony                                                5
manesar                                                        5
subhash nagar                                                  5
sector 30                                                      5
sector 9                                                       5
sector 28                                                      5
sushant lok phase 2                                            5
greenwood city                                                 5
madanpuri                                                      4
shivpuri                                                       4
valley view estate                                             4
vishnu garden                                                  4
new                                                            4
adarsh nagar                                                   4
dharam colony                                                  4
sector 17                                                      4
sector 12a                                                     4
imt manesar                                                    4
bhim nagar                                                     4
surya vihar                                                    4
shivaji nagar                                                  4
devilal colony                                                 4
ravi nagar                                                     4
sector 45                                                      4
sector 36                                                      4
sector 6                                                       4
garhi harsaru                                                  4
suncity                                                        4
krishna colony                                                 4
sector 12                                                      4
baldev nagar                                                   4
bhondsi                                                        4
sector 3a                                                      4
prem nagar                                                     3
sector 27                                                      3
patel nagar                                                    3
sector 17b                                                     3
sector 88b                                                     3
sector 23                                                      3
sector 110 a                                                   3
gandhi nagar                                                   3
sector 73                                                      3
a block sushant lok phase 1                                    3
b block sushant lok phase 1                                    3
sector 17a                                                     3
sector 15                                                      3
laxmi garden                                                   3
mg road                                                        3
shakti nagar                                                   3
sector 8                                                       3
maruti kunj                                                    3
faridabad road                                                 2
sispal vihar                                                   2
rajiv chowk                                                    2
lajpat nagar                                                   2
mayfield garden                                                2
daulatabad                                                     2
samaspur                                                       2
iffco chowk                                                    2
block a surya vihar                                            2
farukhnagar                                                    2
sushant lok                                                    2
ambience island                                                2
new basti                                                      2
sector 15 part 1                                               2
pratap nagar                                                   2
shankar vihar                                                  2
sector 41                                                      2
hira nagar                                                     2
sheetla colony                                                 2
shanti nagar                                                   2
acharya puri                                                   2
sector 24                                                      2
golf course ext road                                           2
surat nagar phase 2                                            2
golf course road                                               2
sohna  road                                                    2
sector-11 sohna                                                2
new palam vihar phase 1                                        2
west rajiv nagar                                               2
bhawani enclave                                                2
surat nagar                                                    2
sector 15 part 2                                               2
mohan nagar                                                    2
rosewood                                                       2
sector 21                                                      2
nars                                                           2
sector-2 sohna                                                 2
, delhi ncr                                                    2
bissar                                                         2
new palam vihar phase 2                                        2
manohar nagar                                                  2
sector 32                                                      2
near sector 1 market                                           1
hno 13 sagar enclave sura                                      1
tekchand nagar                                                 1
godrej aria , sector 79 ,                                      1
ats marigold                                                   1
ashok vihar phase 3                                            1
carterpuri village                                             1
old delhi road, opp sector-14                                  1
sector 17c                                                     1
sector-35 sohna                                                1
sector 13                                                      1
khandsa                                                        1
sector 21a faridabad                                           1
sector 4 urban estate                                          1
south city                                                     1
saroop garden rajendra park                                    1
begampur khatola                                               1
sector 5 chowk                                                 1
sai kunj                                                       1
kanahi                                                         1
heritage city                                                  1
sector 9b                                                      1
new colony, sector 7                                           1
cyber city                                                     1
block h ashok vihar phase iii extension                        1
block g sector-57                                              1
ashok vihar phase i                                            1
huda saraswati vihar                                           1
sector-5 sheetla colony                                        1
sultanpur                                                      1
near nand hospital                                             1
ravi nager basai road                                          1
ansal's palam vihar                                            1
near pataudi chowk                                             1
udyog vihar phase 1                                            1
jacobpura near sadar bazar                                     1
near khandsa road                                              1
rajiv colony                                                   1
laxman vihar, railway road,                                    1
vir nagar                                                      1
dhankot                                                        1
sector 42                                                      1
near euro                                                      1
alipur                                                         1
new jyoti park                                                 1
v block dlf phase 3                                            1
bptp                                                           1
rattan garden                                                  1
sec 3 bhim vihar part 1 bhimgher kheri                         1
mahalaxmi garden, rajendra place                               1
anand garden, sector-105                                       1
g block dlf city phase 1                                       1
civil l                                                        1
ram nagar                                                      1
bhora kalan                                                    1
nirvana country pocket h                                       1
damdma                                                         1
garauli kalan                                                  1
om nagar                                                       1
naharpur rupa                                                  1
gopal nagar, garhi ghasita, sonipat                            1
jat colony,fazilpur/taj nagar road                             1
laxmna vihar, phase 2                                          1
shivji park colony                                             1
sector 37b                                                     1
sector 37a                                                     1
part 3 sector 5                                                1
devi lal colony gali no 12 gurgaon nr omkar public school      1
urban estate, sector 5                                         1
kheri                                                          1
sector-7 hous                                                  1
saraswati enclave                                              1
mahavir pura                                                   1
lucknow                                                        1
sadar bazar                                                    1
b1 block sector 57                                             1
park view                                                      1
bhimgarh kheri phase 3                                         1
sector-5 sohna                                                 1
pataudi road                                                   1
hsiidc plot sector 1 imt manesar                               1
Name: count, dtype: int64

In [15]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('shanti nagar','sector 11')

In [16]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [17]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [18]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [19]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [20]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [21]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [22]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [23]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [24]:
df['sector'].value_counts().shape

(232,)

In [25]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
703,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2605,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
3486,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
3828,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN

In [26]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'
df.loc[3040,'sector'] = 'sector 2'
df.loc[[540,3802],'sector'] = 'sector 7'
df.loc[[3790],'sector'] = 'sector 3'

In [27]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
478,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
494,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
620,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
1085,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1856,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."

In [28]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [29]:
df.shape

(3807, 21)

In [30]:
df.duplicated().sum()

0

In [31]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,sector 37d,1.60,7302.0,2191.0,Super Built up area 2191(203.55 sq.m.)Built Up...,4,3,3+,others,"A701, Sector 37D Gurgaon, Gurgaon, Haryana",7.0,North,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",This is a super luxury property which is situa...,"['1 Wardrobe', '5 Fan', '1 Exhaust Fan', '21 L...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1,4 BHK Flat in Sector 1A IMT Manesar,flat,dlf express greens,manesar,1.60,6808.0,2350.0,Carpet area: 2350 (218.32 sq.m.),4,6,3+,"study room,pooja room,servant room","Sector 1A IMT Manesar, Gurgaon, Haryana",4.0,North-East,1 to 5 Year Old,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",East facing and cornet flat plus also park fac...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction3.5 out ..."
2,3 BHK Flat in Sector 82 Gurgaon,flat,mapsko royale ville,sector 82,1.12,8000.0,1400.0,Super Built up area 1790(166.3 sq.m.)Built Up ...,3,4,2,"pooja room,servant room","000, Sector 82 Gurgaon, Gurgaon, Haryana",6.0,North-West,1 to 5 Year Old,"['Sapphire 83 Mall', 'Golf Course Ext Rd', ""St...",Mapsko royale ville is one of gurgaon's most s...,"['4 Fan', '1 Exhaust Fan', '7 Light', '1 Modul...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction3 out ..."
3,3 BHK Flat in Sector 90 Gurgaon,flat,dlf regal gardens,sector 90,1.25,7339.0,1703.0,Super Built up area 1703(158.21 sq.m.),3,3,3,servant room,"123, Sector 90 Gurgaon, Gurgaon, Haryana",28.0,North,5 to 10 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",This 3 bhk apartment is available for sale in ...,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction4.5 out ..."
4,3 BHK Flat in Sector 92 Gurgaon,flat,sare green parc,sector 92,0.85,6741.0,1261.0,Built Up area: 1261 (117.15 sq.m.),3,2,2,not available,"Sector 92, Sector 92 Gurgaon, Gurgaon, Haryana",14.0,NaN,undefined,"['Huda city centre metro station', 'Iffco chow...",Multistorey apartment is available for sale. I...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."

In [32]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [33]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
2462,flat,shapoorji pallonji joyville gurugram,sector 102,0.95,10383.0,915.0,Built Up area: 915 (85.01 sq.m.)Carpet area: 8...,2,2,2,not available,14.0,North-West,undefined,NaN,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
2229,flat,mapsko mount ville,sector 79,1.85,9641.0,1919.0,Super Built up area 1815(168.62 sq.m.),3,4,3,"pooja room,servant room",21.0,NaN,0 to 1 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...","['1 Stove', '1 Light', '1 AC', '1 Chimney', '1...","['Feng Shui / Vaastu Compliant', 'Security / F..."
3744,flat,tulip violet,sector 69,1.90,9452.0,2010.0,Super Built up area 2010(186.74 sq.m.)Carpet a...,4,4,2,store room,6.0,West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...","['1 Exhaust Fan', '1 Modular Kitchen', 'No AC'...","['Water purifier', 'Centrally Air Conditioned'..."
1833,flat,indiabulls enigma,sector 110,4.00,9851.0,4061.0,Built Up area: 3350 (311.23 sq.m.),4,4,3,not available,17.0,NaN,0 to 1 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",NaN,NaN
100,flat,dlf new town heights,sector 90,1.60,6768.0,2364.0,Super Built up area 2364(219.62 sq.m.),4,4,3+,"servant room,pooja room",10.0,West,1 to 5 Year Old,"['Manish Gallexie 91', 'NH-8 IMT Manesar', 'RH...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ..."

In [ ]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [34]:
df.duplicated().sum()

121

In [36]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)